import os
import time
import requests

OKTA_DOMAIN = "https://trial-1602807.okta.com"
API_TOKEN = os.environ.get("OKTA_API_TOKEN")

headers = {
    "Accept": "application/json",
    "Content-Type": "application/json",
    "Authorization": f"SSWS {API_TOKEN}"
}

def generate_system_logs():
    print(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] Generating visible Okta System Log events...")

    # 1. Ping API Token (Generates "system.api_token.use" in System Logs)
    print("  -> Triggering API token authentication log...")
    requests.get(f"{OKTA_DOMAIN}/api/v1/users/me", headers=headers)
    time.sleep(1)

    # 2. Trigger Event Hook Test (Generates "system.event_hook.test" in System Logs)
    print("  -> Creating synthetic system log entry via Event Hook test...")
    event_hook_payload = {
        "eventType": "user.session.start",
        "message": "Automated test event generated by GitHub Actions cron"
    }
    # Standard Okta endpoint to force audit log event creation
    requests.post(f"{OKTA_DOMAIN}/api/v1/eventHooks/test", headers=headers, json=event_hook_payload)
    time.sleep(1)

    # 3. Request System Logs query (Generates log access audit record)
    print("  -> Querying logs to register audit event...")
    requests.get(f"{OKTA_DOMAIN}/api/v1/logs?limit=5", headers=headers)

    print("Done! Events have been sent to Okta System Log.")

if __name__ == "__main__":
    generate_system_logs()
